import { RepositoryData } from '../types/schema';

export const mockRepositoryData: RepositoryData = {
  repository: {
    name: 'test-repo',
    path: '/test/path',
    default_branch: 'main',
    languages: ['python', 'javascript', 'typescript'],
    total_files: 5,
    total_lines: 1000,
    created_at: '2023-01-01T00:00:00Z',
    updated_at: '2023-12-01T00:00:00Z',
  },
  files: [
    {
      id: 'file1',
      name: 'main.py',
      path: 'src/main.py',
      type: 'file',
      extension: 'py',
      size: 500,
      lines: 50,
      depth: 1,
      created_at: '2023-01-01T00:00:00Z',
      updated_at: '2023-06-01T00:00:00Z',
      components: [
        {
          id: 'comp1',
          name: 'MainClass',
          type: 'class',
          line_start: 10,
          line_end: 30,
          components: [
            {
              id: 'comp2',
              name: 'method1',
              type: 'method',
              line_start: 15,
              line_end: 20,
            },
          ],
        },
        {
          id: 'comp3',
          name: 'helper_function',
          type: 'function',
          line_start: 35,
          line_end: 45,
        },
      ],
    },
    {
      id: 'file2',
      name: 'utils.js',
      path: 'src/utils.js',
      type: 'file',
      extension: 'js',
      size: 300,
      lines: 30,
      depth: 1,
      created_at: '2023-02-01T00:00:00Z',
      updated_at: '2023-07-01T00:00:00Z',
      components: [
        {
          id: 'comp4',
          name: 'utilFunction',
          type: 'function',
          line_start: 5,
          line_end: 15,
        },
      ],
    },
    {
      id: 'file3',
      name: 'styles.css',
      path: 'src/styles.css',
      type: 'file',
      extension: 'css',
      size: 200,
      lines: 20,
      depth: 1,
      created_at: '2023-03-01T00:00:00Z',
      updated_at: '2023-08-01T00:00:00Z',
    },
    {
      id: 'dir1',
      name: 'components',
      path: 'src/components',
      type: 'directory',
      size: 0,
      lines: 0,
      depth: 1,
      created_at: '2023-01-01T00:00:00Z',
      updated_at: '2023-09-01T00:00:00Z',
    },
    {
      id: 'file4',
      name: 'README.md',
      path: 'README.md',
      type: 'file',
      extension: 'md',
      size: 100,
      lines: 10,
      depth: 0,
      created_at: '2023-01-01T00:00:00Z',
      updated_at: '2023-10-01T00:00:00Z',
    },
  ],
  relationships: [
    {
      source: 'file1',
      target: 'file2',
      type: 'import',
      strength: 1,
      metadata: {
        line_number: 1,
        import_statement: 'import utils from "./utils.js"',
      },
    },
    {
      source: 'file1',
      target: 'file3',
      type: 'filesystem_proximity',
      strength: 0.8,
      metadata: {
        distance: 1,
      },
    },
    {
      source: 'file2',
      target: 'file3',
      type: 'semantic_similarity',
      strength: 0.6,
      metadata: {
        similarity_score: 0.6,
      },
    },
    {
      source: 'comp1',
      target: 'comp4',
      type: 'call',
      strength: 1,
      metadata: {
        line_number: 18,
        call_statement: 'utils.utilFunction()',
      },
    },
    {
      source: 'dir1',
      target: 'file1',
      type: 'contains',
      strength: 1,
      metadata: {},
    },
  ],
  commits: [
    {
      id: 'commit1',
      message: 'Initial commit',
      author: 'Test Author',
      date: '2023-01-01T00:00:00Z',
      files_changed: ['file1', 'file4'],
    },
    {
      id: 'commit2',
      message: 'Add utils and styles',
      author: 'Test Author',
      date: '2023-02-01T00:00:00Z',
      files_changed: ['file2', 'file3'],
    },
  ],
};

export const emptyRepositoryData: RepositoryData = {
  repository: {
    name: 'empty-repo',
    path: '/empty/path',
    default_branch: 'main',
    languages: [],
    total_files: 0,
    total_lines: 0,
    created_at: '2023-01-01T00:00:00Z',
    updated_at: '2023-01-01T00:00:00Z',
  },
  files: [],
  relationships: [],
  commits: [],
};

export const largeRepositoryData: RepositoryData = {
  repository: {
    name: 'large-repo',
    path: '/large/path',
    default_branch: 'main',
    languages: ['python', 'javascript', 'typescript', 'java', 'cpp'],
    total_files: 100,
    total_lines: 10000,
    created_at: '2023-01-01T00:00:00Z',
    updated_at: '2023-12-01T00:00:00Z',
  },
  files: Array.from({ length: 50 }, (_, i) => ({
    id: `file${i + 1}`,
    name: `file${i + 1}.py`,
    path: `src/file${i + 1}.py`,
    type: 'file' as const,
    extension:
      i % 5 === 0 ? 'py' : i % 5 === 1 ? 'js' : i % 5 === 2 ? 'ts' : i % 5 === 3 ? 'java' : 'cpp',
    size: Math.floor(Math.random() * 1000) + 100,
    lines: Math.floor(Math.random() * 100) + 10,
    depth: Math.floor(Math.random() * 3) + 1,
    created_at: '2023-01-01T00:00:00Z',
    updated_at: '2023-06-01T00:00:00Z',
  })),
  relationships: Array.from({ length: 100 }, (_, i) => ({
    source: `file${(i % 49) + 1}`,
    target: `file${((i + 1) % 49) + 1}`,
    type: i % 3 === 0 ? 'import' : i % 3 === 1 ? 'filesystem_proximity' : 'semantic_similarity',
    strength: Math.random(),
    metadata: {},
  })),
  commits: [],
};
